/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'intro',
    'primeiros-passos',
    'conceitos-importantes',
 
    {
      type: 'category',
      label: 'Guias',
      items: [
          {type: 'autogenerated', dirName: 'guias'},
      ],
    },

   
    {
      type: 'category',
      label: 'Recursos adicionais',
      items: [
          {type: 'autogenerated', dirName: 'recursos-adicionais'},
      ],
    },  

    {type: 'autogenerated', dirName: 'recursos-gerais'},

  
  ],
  

  changeLog: [
    {
      type: 'autogenerated',
      dirName: 'release-notes',
    },
  ],


  //opcao2: [{type: 'autogenerated', dirName: './opc2'}],

  // But you can create a sidebar manually
  
  // sidebar1: [
  //   'intro',
  //   'como-comecar',
  //   {
  //     type: 'category',
  //     label: 'Guias',
  //     items: [
  //       {
  //         type: 'category',
  //         label: 'Web',
  //         items: [
  //           'guias/web/reconhecimento-facial/guia'
    
  //         ],
  //       },

  //     ],
  //   },


  // ],



   
};

module.exports = sidebars;
